apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2048
  template:
    metadata:
      labels:
        app: 2048
    spec:
      containers:
      - name: 2048
        image: tejubagalad/2048:latest	
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: 2048-service
spec:
  selector:
    app: 2048
  type: NodePort
  ports:
    - port: 80
      targetPort: 80

